[meta]
canonical = "https://cardo.so"
version = "1.0.0"
lastModified = "2024-04-12"

[basics]
url = "https://cardo.so"
name = "Matheus Cardoso"
label = "Software Engineer"
email = "matheus@cardo.so"
summary = '''
Highly skilled Developer Advocate and Full Stack Engineer with extensive experience in developing and advocating for state-of-the-art technology solutions.
Passionate about improving development experience and obsessed with DevX, Matheus holds proven expertise in data analysis, software development across various stacks, and data security.
He is a strong advocate for open-source software and has a proven track record of building and maintaining developer communities.
'''

[[basics.profiles]]
network = "GitHub"
username = "cardoso"
url = "https://github.com/cardoso"

[[basics.profiles]]
network = "LinkedIn"
username = "cardosodev"
url = "https://www.linkedin.com/in/cardosodev"

[[basics.profiles]]
network = "Twitter"
username = "cardosodev"
url = "https://twitter.com/cardosodev"

[[work]]
name = "SecurityScorecard"
url = "https://securityscorecard.com"
location = "New York, NY"
description = "SecurityScorecard is a cybersecurity rating and continuous risk monitoring platform."
position = "Full Stack Engineer"
startDate = "2023"
summary = "As a full stack engineer in the Sales Enablement department under the Marketing division, I built new automations to deliver value quickly to prospects, designed reports, assisted in customer meetings, and created demos to showcase cutting-edge threat research and intelligence offerings."

[[work]]
name = "Bitmovin"
url = "https://bitmovin.com"
location = "San Francisco, CA"
description = "Bitmovin is a multimedia technology company that provides services that transcode digital video and audio to streaming formats using cloud computing."
position = "Senior Developer Advocate"
startDate = "2021"
endDate = "2023"
summary =  "Under the solutions department, I built and launched the official community platform, I helped drive decisions that improve Developer Experience, built in integrations to facilitate the interface between developers and the company, as well as tightened the relationship between our partners."
[[work]]
name = "Stream"
url = "https://getstream.io"
location = "Boulder, CO"
description = "Stream is an API for building scalable and personalized feeds and chat."
position = "Senior Developer Advocate"
startDate = "2020"
endDate = "2021"
summary =  "I was responsible for building and maintaining the developer community, creating content, and providing technical support to developers using the Stream API. I also worked closely with the product team to provide feedback and help shape the product roadmap."

[[work]]
name = "Virgil Security"
url = "https://virgilsecurity.com"
location = "Manassas, VA"
description = "Virgil Security is a cryptographic services company that provides easy-to-use cryptographic software and services."
position = "Developer Relations Engineer"
startDate = "2019"
endDate = "2020"
summary = "I implemented DevRel practices and culture, as well as helped developers and founders on a daily basis build secure solutions that need to comply with HIPAA and GDPR."

[[work]]
name = "Rocket.Chat"
url = "https://rocket.chat"
location = "Porto Alegre, Brazil"
description = "Rocket.Chat is an open-source team communication platform."
position = "iOS Engineer"
startDate = "2017"
endDate = "2019"
summary = "I was in charge of maintaining and developing new features for the iOS App in Swift and Objective-C, writing unit tests and managing Open Source contributions."

[[work]]
name = "Apple Developer Academy"
url = "https://developer.apple.com/academies/"
location = "Fortaleza, Brazil"
description = "Apple Developer Academy is an internship program created by Apple to train Developers for Apple Platforms."
position = "iOS Engineer"
startDate = "2016"
endDate = "2017"
summary = "I was in charge of developing new Apps and back-end services for iOS, Apple TV and Apple Watch."
